import { useState, useMemo } from 'react';
import { useApp } from '../context/AppContext';
import { useNavigate } from 'react-router-dom';
import { formatRelativeTime, formatDateTime } from '../utils/formatters';
import { AlertType, Alert } from '../types';
import {
  AlertTriangle, Shield, CheckCheck, Filter, Search, Route as RouteIcon,
  Brain, ExternalLink, Bell, Clock, AlertCircle, ShieldAlert, CheckCircle
} from 'lucide-react';

export default function AlertCenter() {
  const { state, dispatch } = useApp();
  const navigate = useNavigate();

  const [severityFilter, setSeverityFilter] = useState<string>('all');
  const [readFilter, setReadFilter] = useState<'all' | 'unread' | 'read'>('all');
  const [searchQuery, setSearchQuery] = useState<string>('');

  // Unread count
  const unreadCount = useMemo(() => state.alerts.filter(a => !a.read).length, [state.alerts]);
  const criticalCount = useMemo(() => state.alerts.filter(a => a.type === 'critical').length, [state.alerts]);

  // Filtered alerts
  const filteredAlerts = useMemo(() => {
    return state.alerts.filter(a => {
      if (severityFilter !== 'all' && a.type !== severityFilter) return false;
      if (readFilter === 'unread' && a.read) return false;
      if (readFilter === 'read' && !a.read) return false;
      if (searchQuery) {
        const q = searchQuery.toLowerCase();
        if (
          !a.title.toLowerCase().includes(q) &&
          !a.message.toLowerCase().includes(q) &&
          !a.category.toLowerCase().includes(q) &&
          !(a.relatedAccountId && a.relatedAccountId.toLowerCase().includes(q))
        ) {
          return false;
        }
      }
      return true;
    });
  }, [state.alerts, severityFilter, readFilter, searchQuery]);

  // Mark all read
  const handleMarkAllRead = () => {
    state.alerts.forEach(a => {
      if (!a.read) {
        dispatch({ type: 'MARK_ALERT_READ', id: a.id });
      }
    });
    dispatch({
      type: 'ADD_TOAST',
      toast: { id: Date.now().toString(), message: 'All alerts marked as read', type: 'info' }
    });
  };

  // Preemptive Freeze from Alert
  const handleFreeze = (accountId: string, alertId: string) => {
    dispatch({ type: 'FREEZE_ACCOUNT', id: accountId });
    dispatch({ type: 'MARK_ALERT_READ', id: alertId });
    dispatch({
      type: 'ADD_TOAST',
      toast: {
        id: Date.now().toString(),
        message: `Account ${accountId} successfully frozen via NPCI Real-Time Intervention`,
        type: 'success',
      },
    });
  };

  return (
    <div style={{ maxWidth: 1200, margin: '0 auto' }}>
      {/* Page Header */}
      <div className="page-header">
        <div>
          <h1 className="page-title">Alert & Threat Center</h1>
          <p className="page-subtitle">Real-time alerts generated by mule detection and next-hop rapid drain monitors</p>
        </div>

        <div style={{ display: 'flex', gap: 8 }}>
          {unreadCount > 0 && (
            <button className="btn btn-ghost btn-sm" onClick={handleMarkAllRead}>
              <CheckCheck size={14} /> Mark All as Read
            </button>
          )}
        </div>
      </div>

      {/* KPI Bar */}
      <div className="metrics-grid" style={{ marginBottom: 20 }}>
        <div className="metric-card danger">
          <div className="metric-label">
            <ShieldAlert size={12} /> Critical Threats
          </div>
          <div className="metric-value" style={{ color: 'var(--risk-critical)' }}>
            {criticalCount}
          </div>
          <div className="metric-trend up">Urgent Next-Hop Interventions</div>
        </div>

        <div className="metric-card warning">
          <div className="metric-label">
            <Bell size={12} /> Unread Notifications
          </div>
          <div className="metric-value" style={{ color: 'var(--warning)' }}>
            {unreadCount}
          </div>
          <div className="metric-trend neutral">Requires Review</div>
        </div>

        <div className="metric-card info">
          <div className="metric-label">
            <Shield size={12} /> Preemptively Frozen
          </div>
          <div className="metric-value" style={{ color: 'var(--frozen)' }}>
            {state.frozenAccounts.size}
          </div>
          <div className="metric-trend down">Accounts Protected</div>
        </div>

        <div className="metric-card accent">
          <div className="metric-label">
            <Clock size={12} /> Active Monitors
          </div>
          <div className="metric-value">5</div>
          <div className="metric-trend neutral">All Pipelines Healthy</div>
        </div>
      </div>

      {/* Filter Bar */}
      <div className="filter-bar" style={{ background: 'var(--bg-secondary)', padding: '10px 16px', borderRadius: 'var(--radius-md)', border: '1px solid var(--border)', marginBottom: 20 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, flex: 1 }}>
          <Search size={14} style={{ color: 'var(--text-tertiary)' }} />
          <input
            type="text"
            className="filter-input"
            placeholder="Search alerts by title, description, or account ID..."
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            style={{ width: 300 }}
          />
        </div>

        <select className="filter-select" value={severityFilter} onChange={e => setSeverityFilter(e.target.value)}>
          <option value="all">All Severities</option>
          <option value="critical">Critical Only</option>
          <option value="high">High Only</option>
          <option value="medium">Medium Only</option>
          <option value="low">Low Only</option>
        </select>

        <select className="filter-select" value={readFilter} onChange={e => setReadFilter(e.target.value as any)}>
          <option value="all">All Status</option>
          <option value="unread">Unread Only</option>
          <option value="read">Read Only</option>
        </select>
      </div>

      {/* Alerts List */}
      {filteredAlerts.length > 0 ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {filteredAlerts.map(alert => {
            const isFrozen = alert.relatedAccountId && state.frozenAccounts.has(alert.relatedAccountId);

            return (
              <div
                key={alert.id}
                className={`alert-card ${alert.type} ${!alert.read ? 'unread' : ''}`}
                style={{
                  display: 'flex',
                  alignItems: 'flex-start',
                  justifyContent: 'space-between',
                  background: 'var(--bg-secondary)',
                  padding: 18,
                }}
              >
                <div style={{ display: 'flex', gap: 16, flex: 1 }}>
                  {/* Left severity icon */}
                  <div className={`alert-icon ${alert.type}`} style={{ width: 36, height: 36 }}>
                    {alert.type === 'critical' ? (
                      <AlertCircle size={20} />
                    ) : alert.type === 'high' ? (
                      <AlertTriangle size={20} />
                    ) : (
                      <Bell size={20} />
                    )}
                  </div>

                  {/* Body */}
                  <div className="alert-body" style={{ flex: 1 }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
                      <span className="alert-title" style={{ fontSize: 14 }}>{alert.title}</span>
                      <span className={`risk-badge ${alert.type}`}>{alert.type.toUpperCase()}</span>
                      <span style={{ fontSize: 11, background: 'var(--bg-tertiary)', padding: '2px 8px', borderRadius: 4, color: 'var(--text-tertiary)' }}>
                        {alert.category}
                      </span>
                      {!alert.read && (
                        <span style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--accent)' }} />
                      )}
                    </div>

                    <p className="alert-message" style={{ fontSize: 13, color: 'var(--text-secondary)', marginBottom: 10 }}>
                      {alert.message}
                    </p>

                    {/* Metadata & Associated Entities */}
                    <div className="alert-meta">
                      <span style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                        <Clock size={12} /> {formatRelativeTime(alert.timestamp)} ({formatDateTime(alert.timestamp)})
                      </span>

                      {alert.relatedAccountId && (
                        <span style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                          Target: <strong className="mono" style={{ color: 'var(--text-primary)' }}>{alert.relatedAccountId}</strong>
                          {isFrozen && (
                            <span style={{ color: 'var(--frozen)', fontWeight: 600, fontSize: 10 }}>[FROZEN]</span>
                          )}
                        </span>
                      )}

                      {alert.relatedCaseId && (
                        <span style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                          Case: <strong className="mono" style={{ color: 'var(--accent)' }}>{alert.relatedCaseId}</strong>
                        </span>
                      )}
                    </div>
                  </div>
                </div>

                {/* Right Quick Actions */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: 6, alignItems: 'flex-end', marginLeft: 16 }}>
                  {alert.relatedAccountId && !isFrozen && (
                    <button
                      className="btn btn-sm btn-danger"
                      onClick={() => handleFreeze(alert.relatedAccountId!, alert.id)}
                    >
                      <Shield size={12} /> Preemptive Freeze
                    </button>
                  )}

                  {alert.relatedCaseId && (
                    <button
                      className="btn btn-sm btn-ghost"
                      onClick={() => {
                        dispatch({ type: 'MARK_ALERT_READ', id: alert.id });
                        navigate(`/trail/${alert.relatedCaseId}`);
                      }}
                    >
                      <RouteIcon size={12} /> Trace Trail
                    </button>
                  )}

                  {alert.relatedAccountId && (
                    <button
                      className="btn btn-sm btn-ghost"
                      onClick={() => {
                        dispatch({ type: 'MARK_ALERT_READ', id: alert.id });
                        dispatch({ type: 'SELECT_ACCOUNT', id: alert.relatedAccountId! });
                        navigate('/mule-intelligence');
                      }}
                    >
                      <Brain size={12} /> Mule Intelligence
                    </button>
                  )}

                  {!alert.read && (
                    <button
                      className="btn btn-sm btn-ghost"
                      style={{ fontSize: 11, padding: '2px 8px', color: 'var(--text-tertiary)' }}
                      onClick={() => dispatch({ type: 'MARK_ALERT_READ', id: alert.id })}
                    >
                      Mark Read
                    </button>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      ) : (
        <div className="card">
          <div className="empty-state">
            <CheckCircle size={36} className="empty-state-icon" style={{ color: 'var(--success)', opacity: 0.8 }} />
            <div className="empty-state-title">No Alerts Match Filter</div>
            <p className="empty-state-message">
              All monitored transactions and accounts are within normal variance thresholds.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
